site_name: UNE Wiki
site_description: The UNE Wiki
site_url: https://une-mc.github.io/wiki

theme:
  name: material
  language: en
  logo: _assets/logo.png
  favicon: _assets/logo.png
  features:
    - navigation.indexes
    - navigation.sections
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: "#00132c"
      accent: "#00132c"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: "#00132c"
      accent: "#00132c"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.superfences

plugins:
  - search
  - awesome-pages
  - redirects

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Categories:
      - Organisations:
          - Commonwealth of Independent States: organisations/cis.md
      - Countries:
          - Austria: countries/austria.md
          - Belarus: countries/belarus.md
          - Luxembourg: countries/luxembourg.md
          - North Macedonia: countries/fyrom.md
          - Russia: countries/russian-federation.md
          - Ukraine: countries/ukraine.md
      - People:
          - Russia:
            - Hugo: people/russia/hugo.md
            - The0nlyBob: people/russia/theonlybob.md
            - Xee: people/russia/xee.md
      - Politics:
          - Russia:
              - Overview: politics/russia/_index.md
              - Institutions:
                  - Supreme Soviet: politics/russia/institutions/supreme-soviet.md
                  - KGB: politics/russia/institutions/kgb.md
              - Parties:
                  - KPRF (Communist Party of the Russian Federation): politics/russia/parties/kprf.md
                  - RSDRP (Russian Social Democratic Labour Party): politics/russia/parties/rsdrp.md
                  - Yabloko: politics/russia/parties/yabloko.md
                  - Rodina: politics/russia/parties/rodina.md
                  - LDPR (Liberal Democratic Party of Russia): politics/russia/parties/ldpr.md
              - Legislature:
                  - 6th Legislature: politics/russia/legislatures/VI.md
                  - 5th Legislature: politics/russia/legislatures/V.md
                  - 4th Legislature: politics/russia/legislatures/IV.md
                  - 3rd Legislature: politics/russia/legislatures/III.md
                  - 2nd Legislature: politics/russia/legislatures/II.md
                  - 1st Legislature: politics/russia/legislatures/I.md
              - Elections:
                  - 2024: politics/russia/elections/2024.md
                  - 2025: politics/russia/elections/2025.md
              - Constitutions:
                  - 2024 Constitution: politics/russia/constitutions/2024.md
                  - Summer 2025 debates: politics/russia/constitutions/summer-2025.md
                  - September Constitution: politics/russia/constitutions/september-constitution.md 
      - Geography:
          - Russia:
              - Cities:
                  - KÃ¶nigsberg: geography/russia/cities/konigsberg.md
                  - Moscow: geography/russia/cities/moscow.md
                  - St. Petersburg: geography/russia/cities/st-petersburg.md
                  - Smolensk: geography/russia/cities/smolensk.md
              - Regions:
                  - Republic of Karelia: geography/russia/regions/karelia.md
                  - Pridnestrovie : geography/russia/regions/pridnestrovie.md
                  - Smolensk Oblast: geography/russia/regions/smolensk.md
                  - Tver Oblast: geography/russia/regions/tver.md
      - Economy:
          - Russia:
              - Companies:
                  - United Resources Corporation: economy/russia/companies/ork.md
                  - Rostec: economy/russia/companies/rostec.md
                  - Russian Railways: economy/russia/companies/rzd.md
                  - Vodka Monopoly: economy/russia/companies/vodka-monopoly.md
          - Switzerland: 
              - Companies:
                  - SNHK: economy/switzerland/companies/snhk.md
          - Ukraine:
              - Companies:
                  - UBP: economy/ukraine/companies/ubp.md