site_name: Большая советская энциклопедия
site_description: State encyclopaedia. Approved by the Ministry of Culture.
site_url: https://billy-teraire.github.io/bse

theme:
  name: material
  language: en
  logo: _assets/logo.png
  favicon: _assets/logo.png
  features:
    - navigation.indexes
    - navigation.sections
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.superfences

plugins:
  - search
  - awesome-pages
  - redirects

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Categories:
      - Organisations:
          - Commonwealth of Independent States: organisations/cis.md
      - Countries:
          - Russia: countries/russian-federation.md
          - Ukraine: countries/ukraine.md
          - Belarus: countries/belarus.md
          - Pridnestrovie: countries/pridnestrovie.md
          - Austria: countries/austria.md
      - People:
          - Russia:
            - Hugo: people/russia/hugo.md
            - Xee: people/russia/xee.md
      - Politics:
          - Russia:
              - Overview: politics/russia/_index.md
              - Institutions:
                  - Supreme Soviet: politics/russia/institutions/supreme-soviet.md
                  - KGB: politics/russia/institutions/kgb.md
              - Parties:
                  - KPRF (Communist Party of the Russian Federation): politics/russia/parties/kprf.md
                  - RSDRP (Russian Social Democratic Labour Party): politics/russia/parties/rsdrp.md
                  - Yabloko: politics/russia/parties/yabloko.md
                  - Rodina: politics/russia/parties/rodina.md
                  - LDPR (Liberal Democratic Party of Russia): politics/russia/parties/ldpr.md
              - Elections:
                  - 2024: politics/russia/elections/2024.md
                  - 2025: politics/russia/elections/2025.md
              - Constitutions:
                  - 2024 Constitution: politics/russia/constitutions/2024.md
                  - Summer 2025 debates: politics/russia/constitutions/summer-2025.md
                  - September Constitution: politics/russia/constitutions/september-constitution.md 
      - Geography:
          - Russia:
              - Cities:
                  - Moscow: geography/russia/cities/moscow.md
                  - Smolensk: geography/russia/cities/smolensk.md
              - Regions:
                  - Republic of Karelia: geography/russia/regions/karelia.md
                  - Smolensk Oblast: geography/russia/regions/smolensk.md
                  - Tver Oblast: geography/russia/regions/tver.md
      - Economy:
          - Russia:
              - Companies:
                  - Vodka Monoly: economy/russia/companies/vodka-monopoly.md